version: '3'
services:
  database:
    image: 'mariadb:latest'
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=contocorrente
    ports:
      - 3306:3306
    restart: always
  app:
    image: springboot-docker-container
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/contocorrente?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: password
    build: ./
    depends_on:
      - database
